spring.application.name=sistema-inventario

# Conexion oficial a MySQL en Aiven
spring.datasource.url=jdbc:mysql://mysql-ba88c34-josefernando-24ca.g.aivencloud.com:14513/defaultdb?sslMode=REQUIRED&useSSL=true&trustServerCertificate=true
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_NexKXHP7NttdCg6D0QV
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracion de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081
